apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - name: data
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: ui
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
